title: SCC-MultiApi-Converter - Generate contract-testing code based on AsyncApi and OpenApi specification for SpringBoot projects.
description: Built by Corunet, SCC-Maven-Plugin is an open-source, Spring Cloud Contract generator extension that allows generating contract-testing code based on AsyncApi and OpenApi specifications.
twitter:
  username: corunet
  card: summary
image: /assets/corunet-logo.svg
logo: /assets/corunet-logo.svg
# show_downloads: true
# google_analytics:
theme: jekyll-theme-tactile
